server:
  port: 8081
  servlet:
    context-path: /myportal/



spring:
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/develop_merry_corner_db
    username: root
    password: vamsi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: email-smtp.us-west-2.amazonaws.com
    username: AKIAT3BS7B3VOTDHVRUY
    password: BAxLvGYEOqLAyEP3lShzJcFney89CbvL+RMS3gMY5Jr4
#    TLS COnfiguration
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true
  upload:
    directory: /path/to/upload/directory




